# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pickCoordinates <- function(Dim, N, fe, VT, U) {
    .Call('_gfimm_pickCoordinates', PACKAGE = 'gfimm', Dim, N, fe, VT, U)
}

tsolveAndMultiply <- function(A, C) {
    .Call('_gfimm_tsolveAndMultiply', PACKAGE = 'gfimm', A, C)
}

nullSpace <- function(M) {
    .Call('_gfimm_nullSpace', PACKAGE = 'gfimm', M)
}

QRdecomp <- function(M) {
    .Call('_gfimm_QRdecomp', PACKAGE = 'gfimm', M)
}

